### ISSUE TITLE
timesformer_scenegraph/models/のファイル不足

### ISSUE THREAD

**Issue by nissy-shota** [qiuyue1993/21grp_anet#3]
model.pyの4行目についてです．
```python
from models import resnet, resnet2p1d, pre_act_resnet, wide_resnet, resnext, densenet
```
こちらも先ほど同様に原さんのリポジトリと比較すると，modelsにresnet以外のpyファイルがないのでエラーが出ました．
ただresnetのみ使用予定であれば，import文を修正してしまっても良いと思います．

**Comment by qiuyue1993** [comment]
> model.pyの4行目についてです．
> 
> ```python
> from models import resnet, resnet2p1d, pre_act_resnet, wide_resnet, resnext, densenet
> ```
> 
> こちらも先ほど同様に原さんのリポジトリと比較すると，modelsにresnet以外のpyファイルがないのでエラーが出ました．
> ただresnetのみ使用予定であれば，import文を修正してしまっても良いと思います．

ありがとうございます。import文を修正しました！
